### PR TITLE
Further improvements towards being able to pass the basic review

### LINKED ISSUE #2: Next steps required to pass the bassic review made by the international community
After merging the first pull request, you may do the following:

* Edit buildVars.py and write a longer description (two or three lines).
* Also, change the summary to give a more descriptive title.
* Delete all contents from readme.md and write the add-on documentation in Markdown format. You can use [InputLock](https://github.com/jmdaweb/inputLock) or [Enhanced Aria](https://github.com/jmdaweb/enhancedAria) as examples or starting points.
* In the code, use the `@script` decorator to document your scripts. Type `help(scriptHandler.script)` in the NVDA Python console for more information. The description and category are specially important.
* Add messages for translators above your translatable strings. Again, see the previously linked add-ons for more information and examples.
* If possible, replace win32process.pyd with a native Python module included in NVDA core. Win32process.pyd is a dll, and may fail if Pywin32 version is upgraded.

Regards.

### PR DESCRIPTION
**Pull request by lukaszgo1**
Closes #2 
This PR implements the following:
## Updates to the add-on
Most of the code has been rewritten:
  - It makes maintenance easier - the - previous code was written in a very non-object oriented way
  - the possibility of changing title of the current window, changing process priority and  showing list of hidden windows dropped when moving to Python 3 has been reintroduced
  - All translatable strings are now properly commented and script decorator is used for keyboard commands.
  - As we no longer rely on win32Process I've removed it.
## Other changes:
- We now have proper documentation
- Add-on template has been updated to the latest version
- The file containing hidden windows is now migrated during add-on update.
- I've also bumped version umber to 5.0

### CODE REVIEW

**Comment by lukaszgo1** [comment]
@jmdaweb If you have time could you please take a look? You certainly have more experience with NVDA add-on development than I do.

**Comment by lukaszgo1** [comment]
@ogomez92 This seems to be stalled. I've send you an e-mail some time ago asking for your plans with regard to WinWizard's maintenance but haven't gotten a response yet. I'd love to see it present in the official add-on website one day!

**Comment by ogomez92** [comment]
Hi, yeah, you're probably right. I should stop being lazy and do it,
but then again the project is open source, I'm sure someone else could
do it. I'm not a heavy windows user anymore.

**Comment by lukaszgo1** [comment]
I'm more than happy to take WinWizard's maintenance over. Assuming that you don't mint could you please add me as a collaborator to your repo. that way I can merge this PR, then transfer the repository to my account and continue from there?

**Comment by ogomez92** [comment]
done

**Comment by lukaszgo1** [comment]
@ogomez92 I'm sorry - it turns out that when your not a repository owner you cannot transfer it to the different account. Could you please transfer this repor to the account of mine?

**Comment by lukaszgo1** [comment]
@ogomez92   Sorry for bothering you, but as I've explained above only repository owner can transfer the repository to the different account. Could you transfer this repo to my GitHub account?

**Comment by lukaszgo1** [comment]
Hello @ogomez92. As I've explained above I'd like to  publish WinWizard in the official add-ons repo and it would be way easier if I'd have this repo transferred to my GitHub account - I cannot do that myself as collaborators don't have such permissions. If you don't want to do that for whatever reason its fine - just let me know, but if that is okay with you i'd appreciate if you can transfer it over as it is a very quick process.

**Comment by lukaszgo1** [comment]
@ogomez92 Ping. Since you're not interested in maintaining WinWizard yourself it is only logical to let others do it and as I said I'd rather do this having the repository transferred to my account than working from a fork or from the repo on your account.

**Comment by ogomez92** [comment]
done

**Pull request merged**
